#!/usr/bin/python3 -u

# https://roboticsbackend.com/raspberry-pi-gpio-interrupts-tutorial/

import signal
import sys
from gpiozero import Button

if len(sys.argv) < 2:
    print("Usage: gpiomon PIN...\nWhere PIN is a BCM pin number.")
    sys.exit()

def button_pressed_callback(channel):
    print("")

buttons = []

for n in sys.argv[1:]:
    b = Button(n)
    b.when_pressed = lambda n=n: print(n)
    buttons.append(b)

signal.pause()
