#!/usr/bin/python3 -u

import time
import board
import busio
import sys
import adafruit_ads1x15.ads1115 as ADS
from adafruit_ads1x15.analog_in import AnalogIn
from gpiozero import Button

buttons = []

for n in sys.argv[1:]:
    b = Button(n)
    b.when_pressed = lambda n=n: print(n)
    buttons.append(b)

# Create the I2C bus
i2c = busio.I2C(board.SCL, board.SDA)

# Create the ADC object using the I2C bus
ads = ADS.ADS1115(i2c)

# Create single-ended input on channel 0
chan = [AnalogIn(ads, ADS.P0), AnalogIn(ads, ADS.P1), AnalogIn(ads, ADS.P2), AnalogIn(ads, ADS.P3)]

thresh = [3.0, 3.2, 3.0, 2.4]
on = [False, False, False, False]

while True:
    for i in range(4):
        if chan[i].voltage < thresh[i]:
            if not on[i]:
                print("A" + str(i))
            on[i] = True
        else:
            on[i] = False
