#!/usr/bin/python3 -u

import fileinput
from gpiozero import LED

leftpin = 8
rightpin = 25

left = LED(leftpin)
right = LED(rightpin)

for line in fileinput.input():
    line = line.rstrip()

    if line == 'l on':
        left.on()
    if line == 'l off':
        left.off()
    if line == 'r on':
        right.on()
    if line == 'r off':
        right.off()
