#!/usr/bin/perl

use strict;
use warnings;

use IPC::Run qw(start pump finish);

my $fen = join(' ', @ARGV);

my @stockfish = ('./stockfish_10_x64');
my $in;
my $out;

my $h = start \@stockfish, \$in, \$out;
$in = "position fen $fen\ngo nodes 100000\n";
pump $h while length $in;

pump $h until $out =~ /bestmove ([a-h][1-8][a-h][1-8][qrbn]?)/;
finish $h;

print "$1\n";
